DjangoUeditor/urls.py
#coding:utf-8
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import url
else:
    from django.conf.urls.defaults import patterns, url

from views import get_ueditor_controller

urlpatterns = [
    url(r'^controller/$',get_ueditor_controller),
    ]


blog/urls.py
#coding:utf-8
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name ="post_detail"),
    url(r'^category/(?P<pk>\d+)/$', views.CategoryView.as_view(), name="category"),
    url(r'archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'tag/(?P<pk>\d+)/$', views.TagView.as_view(), name='tag'),
    ]

comments/urls.py
#coding:utf-8
from django.conf.urls import url
from . import views

app_name = 'comment'
urlpatterns = [
    url(r'^comment/post/(?P<pk>\d+)/$', views.post_comment, name = 'post_comment'),
        ]

mysite/urls.py
#coding:utf-8
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
#from users import views
from blog import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'users/', include('users.urls')),
    #引入django auth中的url
    url(r'users/', include('django.contrib.auth.urls')),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'ueditor/', include('DjangoUeditor.urls')),
    url(r'blog/',include('blog.urls',namespace = 'blog')),
    url(r'', include('comments.urls', namespace = 'comment')),
    url(r'^search/$', include('haystack.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from users.models import User
from django.db import models
from django.utils.six import python_2_unicode_compatible
from DjangoUeditor.models import UEditorField
from django.urls import reverse
from django.utils.html import strip_tags
#分类表,python_2_unicode_compatible用于兼容python2
@python_2_unicode_compatible
class Category(models.Model):
    cname = models.CharField(max_length = 100)
   
    def __str__(self):
        return self.cname
    
    class Meta:
        db_table = 'category'
        verbose_name = '分类'
        verbose_name_plural = '分类'
#标签表
@python_2_unicode_compatible
class Tag(models.Model):
    tname = models.CharField(max_length = 100)
    
    def __str__(self):
        return self.tname

    class Meta:
        db_table = 'tag'
        verbose_name = '标签'
        verbose_name_plural = '标签'
#文章表
@python_2_unicode_compatible
class Post(models.Model):
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank = True)
    title = models.CharField(max_length = 70)
    body = UEditorField('内容', max_length = 20000, imagePath='images/', filePath='files/', default = u'', blank = True, width=600, height=800)
    excerpt = models.CharField(max_length = 200, blank = True)#摘要
    create_time = models.DateTimeField(auto_now_add = True)
    update_time = models.DateTimeField(auto_now = True)
    author = models.ForeignKey(User)
    
    #点击
    clickCount = models.IntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs = {'pk':self.pk})

    def save(self, *args, **kwargs):
        if not self.excerpt:
            self.excerpt = strip_tags(self.body)[:54]
            super(Post,self).save(*args,**kwargs)

    class Meta:
        db_table = 'post'
        verbose_name = '文章'
        verbose_name_plural = '文章'
        ordering = ['-create_time']

comments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.six import python_2_unicode_compatible
from blog.models import Post

@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length = 50)
    email = models.EmailField(max_length = 255)
    url = models.URLField(blank = True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add = True)

    post = models.ForeignKey(Post)

    def __str__(self):
        return self.text[:20]

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView,DetailView
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,JsonResponse
from models import *
from django.views.decorators.cache import cache_page
import datetime
from comments.forms import CommentForm
from django.db.models import Q

class IndexView(ListView):
    model = Post
    template_name = 'index.html'
    context_object_name = 'post_list'
    paginate_by = 2

class CategoryView(ListView):
    model = Post
    template_name = 'blog/category.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk = self.kwargs.get('pk'))
        return super(CategoryView,self).get_queryset().filter(category=cate)

def post_detail(request, pk):
    template_name = 'blog/detail.html'
    post = get_object_or_404(Post,pk=pk)
    #此处可以使用celery异步进行存储
    post.clickCount +=1
    post.save()

    context = {}
    comment_list = post.comment_set.all()
    form = CommentForm()
    categorys = Category.objects.all()
    context['post'] = post
    context['form'] = form
    context['comment_list'] = comment_list
    context['categorys'] = categorys
    return render(request,template_name,context)

#def category_list(request, category_id):
 #   template_name = 'blog/category.html'
    #categorys = Category.objects.all()
  #  cate = get_object_or_404(Category,pk = category_id)
   # post_list = Post.objects.filter(category=cate)
    #context = {}
    #context['categorys'] = categorys
   # context['post_list'] = post_list
   # return render(request, template_name, context)

#归档
class ArchivesView(ListView):
    model = Post
    template_name = 'blog/archives.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return super(ArchivesView,self).get_queryset().filter(create_time__year = self.kwargs.get('year'))

#标签云
class TagView(ListView):
    model = Post
    template_name = 'blog/tag.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag,pk = self.kwargs.get('pk'))
        return super(TagView,self).get_queryset().filter(tags=tag)

#全文检索
def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'index.html', context = {'error_msg':error_msg})
    
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'index.html', context = {'error_msg':error_msg,
        'post_list':post_list
        })

templates/blog/archives.html
{% extends 'header.html' %}
{% block css %}
    <style>
        .content{
            margin-top:80px;
        }
    </style>
{% endblock %}
{% block content %}
        {% for post in post_list %} 
        <div class="jumbotron">
           <h1 class="text-center">{{post.title}}</h1>
           <div class="text-center">
               <span><a href="{% url 'blog:category' post.category.id%}">{{post.category}}</a></span>
               <span>{{post.create_time}}</span>
               <span>{{post.user.username}}</span>
               <span><a href="{{ post.get_absolute_url }}">评论 
                       <span class="badge">{{post.comment_set.count}}</span></a>
                   <span><a href="{{ post.get_absolute_url }}">阅读 
                           <span class="badge">{{post.clickCount}}</span></a>
           </div>
           <div>{{post.excerpt}}</div>
           <p class="text-right"><a class="btn btn-success btn-sm" href="{{ post.get_absolute_url }}" role="button">进入文章</a></p>
        </div>
        {% empty %}
        <div class="col-xs-9">还没有文章！！！请添加！！！</div>
        {% endfor %}
{% endblock %}

templates/blog/category.html
{% extends 'header.html' %}
{% block css %}
    <style>
        .content{
            margin-top:80px;
        }
    </style>
{% endblock %}
{% block content %}
        {% for post in post_list %} 
        <div class="jumbotron">
           <h1 class="text-center">{{post.title}}</h1>
           <div class="text-center">
               <span><a href="">{{post.category}}</a></span>
               <span>{{post.create_time}}</span>
               <span>{{post.user.username}}</span>
               <span><a href="{{ post.get_absolute_url }}">评论 
                       <span class="badge">{{ post.comment_set.count }}</span></a>
                   <span><a href="{{ post.get_absolute_url }}">阅读 
                           <span class="badge">{{ post.clickCount }}</span></a>
           </div>
           <div>{{post.excerpt}}</div>
           <p class="text-right"><a class="btn btn-success btn-sm" href="{{ post.get_absolute_url }}" role="button">进入文章</a></p>
        </div>
        {% endfor %}
{% endblock %}

templates/blog/detail.html
{% extends 'header.html' %}
{% block content %}
       <h3 class="text-center">{{post.title}}</h3>
       <div class="text-center">
           <span><a href="{% url 'blog:category' post.category.id %}">{{post.category}}</a></span>
           <span>{{post.create_time}}</span>
           <span>{{post.author}}</span>
           <span>评论 
               <span class="badge">{{comment_list | length}}</span>
               <span>阅读 
                   <span class="badge">{{post.clickCount}}</span>
       </div>
       <p></p>
       <div>
        {{post.body | safe }}
       </div>
        <hr>
        <ul class="list-inline">
            <li>标签:</li>
            {% for tag in post.tags.all %}
            <li>{{tag.tname}}</li>
            {% endfor%}
        </ul>
        <br>
       <h3>请发言</h3>
       <form action="{% url 'comment:post_comment' post.id %}" method="post" class ="form-group">
            {% csrf_token %}
            <div class="col-sm-3">
                <label for="{{ form.name.id_for_label }}">名字:</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="col-sm-3 col-sm-offset-1">
                <label for="{{ form.email.id_for_label }}">邮箱:</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="col-sm-3 col-sm-offset-1">
                <label for="{{ form.url.id_for_label }}">URL:</label>
                {{ form.url }}
                {{ form.url.errors }}
            </div>
            <div class="col-sm-12">
                <label {{ form.text.id_for_label }}>评论:</label>
                {{ form.text }}
                {{ form.text.errors }}
                <button class="btn btn-success" type="submit">发表</button>
            </div>
       </form>
       <br>
       <h3>评论列表，共{{comment_list | length}}条评论</h3>
        {% for comment in comment_list %}
        <div class="panel panel-default">
            <div class="panel panel-heading">
            <span>用户:{{ comment.name }}</span> | 
            <time>{{ comment.create_time }}</time>
            <div>
            </div>
            <div class="panel panel-body">
                {{ comment.text }} 
            </div>
        </div>
        {% endfor%}
{% endblock %}

templates/blog/tag.html
{% extends 'header.html' %}
{% block css %}
    <style>
        .content{
            margin-top:80px;
        }
    </style>
{% endblock %}
{% block content %}
        {% for post in post_list %} 
        <div class="jumbotron">
           <h1 class="text-center">{{post.title}}</h1>
           <div class="text-center">
               <span><a href="">{{post.category}}</a></span>
               <span>{{post.create_time}}</span>
               <span>{{post.user.username}}</span>
               <span><a href="{{ post.get_absolute_url }}">评论 
                       <span class="badge">{{ post.comment_set.count }}</span></a>
                   <span><a href="{{ post.get_absolute_url }}">阅读 
                           <span class="badge">{{ post.clickCount }}</span></a>
           </div>
           <div>{{post.excerpt}}</div>
           <p class="text-right"><a class="btn btn-success btn-sm" href="{{ post.get_absolute_url }}" role="button">进入文章</a></p>
        </div>
        {% endfor %}
{% endblock %}