DjangoUeditor/urls.py
#coding:utf-8
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import url
else:
    from django.conf.urls.defaults import patterns, url

from views import get_ueditor_controller

urlpatterns = [
    url(r'^controller/$',get_ueditor_controller),
    ]


blog/urls.py
#coding:utf-8
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name ="post_detail"),
    url(r'^category/(?P<pk>\d+)/$', views.CategoryView.as_view(), name="category"),
    url(r'archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'tag/(?P<pk>\d+)/$', views.TagView.as_view(), name='tag'),
    ]

mysite/urls.py
#coding:utf-8
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
#from users import views
from blog import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'users/', include('users.urls')),
    #引入django auth中的url
    url(r'users/', include('django.contrib.auth.urls')),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'ueditor/', include('DjangoUeditor.urls')),
    url(r'blog/',include('blog.urls',namespace = 'blog')),
    url(r'', include('comments.urls', namespace = 'comment')),
    url(r'^search/$', include('haystack.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

users/urls.py
#coding:utf-8
from django.conf.urls import url
from .import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
        ]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from users.models import User
from django.db import models
from django.utils.six import python_2_unicode_compatible
from DjangoUeditor.models import UEditorField
from django.urls import reverse
from django.utils.html import strip_tags
#分类表,python_2_unicode_compatible用于兼容python2
@python_2_unicode_compatible
class Category(models.Model):
    cname = models.CharField(max_length = 100)
   
    def __str__(self):
        return self.cname
    
    class Meta:
        db_table = 'category'
        verbose_name = '分类'
        verbose_name_plural = '分类'
#标签表
@python_2_unicode_compatible
class Tag(models.Model):
    tname = models.CharField(max_length = 100)
    
    def __str__(self):
        return self.tname

    class Meta:
        db_table = 'tag'
        verbose_name = '标签'
        verbose_name_plural = '标签'
#文章表
@python_2_unicode_compatible
class Post(models.Model):
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank = True)
    title = models.CharField(max_length = 70)
    body = UEditorField('内容', max_length = 20000, imagePath='images/', filePath='files/', default = u'', blank = True, width=600, height=800)
    excerpt = models.CharField(max_length = 200, blank = True)#摘要
    create_time = models.DateTimeField(auto_now_add = True)
    update_time = models.DateTimeField(auto_now = True)
    author = models.ForeignKey(User)
    
    #点击
    clickCount = models.IntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs = {'pk':self.pk})

    def save(self, *args, **kwargs):
        if not self.excerpt:
            self.excerpt = strip_tags(self.body)[:54]
            super(Post,self).save(*args,**kwargs)

    class Meta:
        db_table = 'post'
        verbose_name = '文章'
        verbose_name_plural = '文章'
        ordering = ['-create_time']

comments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.six import python_2_unicode_compatible
from blog.models import Post

@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length = 50)
    email = models.EmailField(max_length = 255)
    url = models.URLField(blank = True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add = True)

    post = models.ForeignKey(Post)

    def __str__(self):
        return self.text[:20]

templates/header.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <meta name=”viewport” content=”width=device-width, initial-scale=1, maximum-scale=1″>
  <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <title>{% block title %}我的博客首页{% endblock %}</title>
  <style type="text/css">
    body{ position:relative;}
  	 .search_post{
  	 	margin:10px;
  	 }
     .content{
        margin-top:80px;
     }
  </style>
  {% block css %}
  {% endblock %}
</head>
<body>

<nav class="nav navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <!--在移动端的时候导航条折叠起来，三横的样式出现，点击该样式可以显示或隐藏导航条上的内容-->
            <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'index' %}" class="navbar-brand">ZYP</a>
        </div>
        <div id="menu" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="{% url 'index' %}">首页</a></li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'login' %}?next={{request.path}}">{{user.username}}</a> 
                </li>
                <li>
                    <a href="{% url 'logout' %}?next={{request.path}}">注销</a>
                </li>    
                {% else %}
                <li>
                    <a href="{% url 'login' %}?next={{request.path}}">登陆</a> 
                 </li>
                 <li>
                 <a href="{% url 'users:register' %}?next={{request.path}}">注册</a>
                 </li>
                 {% endif %}
                <!--下拉菜单功能的实现-->
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    其他<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">添加文章</a></li>
                    <li><a href="#">关于</a></li>
                    <li><a href="#">联系</a></li>
                </ul>
                </li>
                <li class="search_post">
                    <form class="form-inline" action="{% url 'haystack_search' %}" id="searchform">
					  <div class="form-group">
					    <label class="sr-only" for="search_post">search_post</label>
					    <div class="input-group">
					      <input type="search" class="form-control" id="search_post" placeholder="请输入关键词..." name="q" required>
					    </div>
					  </div>
					  <button type="submit" class="btn btn-primary">搜索</button>
					</form>
                </li>
            </ul>
        </div>
    </div>
</nav>
    <div class="container content">
        <div class="col-xs-4">
            <h3>最新文章</h3>
            {% get_recent_posts as recent_posts_list %}
            <ul class="list-group">
            {% for post in recent_posts_list %}
                <li class="list-group-item">
                    <a href="{% url 'blog:post_detail' post.id %}">
                        {{post.title}}
                    </a>
                </li>
            {% empty %}
                <li class="list-group-item">暂无文章</li>
            {% endfor%}
            </ul>
            <h3>归档</h3>
            {% archives as date_list %}
            <ul class="list-group">
                {% for date in date_list %}
                  <li class="list-group-item">
                      <a href="{% url 'blog:archives' date.year date.month %}">{{date.year}}年{{date.month}}月</a>
                  </li>
                  {% endfor %}
            </ul>
            <h3>分类<h3>
            {% get_categorys as categorys_list %}
            <ul class="list-group">
                {% for category in categorys_list %}
                <li class="list-group-item">
                    <span class="badge">{{category.post_set.all | length}}</span>
                    <a href="{% url 'blog:category' category.id %}">{{category.cname}}</a>
                </li>
                {% endfor %}
            </ul>
            <h3>标签云</h3>
            {% get_tags as tag_list %}
            <ul class="list-inline">
                {% for tag in tag_list %}
                <li class="list-group-item">
                    <a href="{% url 'blog:tag' tag.id %}">
                    <span>{{tag.tname}}  </span>
                    <span class="badge">{{tag.post_set.count}}</span>
                    </a>
                </li>
                {% endfor%}  
            </ul>
        </div>
        <div class="col-xs-8">
            {% block content  %}
            {% endblock %}
        </div>
    </div>
  	<script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
  	<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
  	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<script type="text/javascript">
		{% block javascript %}
		{% endblock %}
	</script>
</body>
</html




templates/index.html
{% extends 'header.html' %}
{% block css %}
    <style>
        .content{
            margin-top:80px;
        }
    </style>
{% endblock %}
{% block content %}
        {% if error_msg %}
            <p>{{ error_msg }}</p>
        {% else %}
        {% for post in post_list %} 
        <div class="jumbotron">
           <h1 class="text-center">{{post.title}}</h1>
           <div class="text-center">
               <span><a href="{% url 'blog:category' post.category.id%}">{{post.category}}</a></span>
               <span>{{post.create_time}}</span>
               <span>{{post.user.username}}</span>
               <span><a href="{{ post.get_absolute_url }}">评论 
                       <span class="badge">{{post.comment_set.all | length}}</span></a>
                   <span><a href="{{ post.get_absolute_url }}">阅读 
                           <span class="badge">{{ post.clickCount}}</span></a>
           </div>
           <div>{{post.excerpt}}</div>
           <p class="text-right"><a class="btn btn-success btn-sm" href="{{ post.get_absolute_url }}">进入文章</a></p>
        </div>
        {% empty %}
        <div class="col-xs-9">还没有文章！！！请添加！！！</div>
        {% endfor %}
        {% endif %}
        <nav aria-label="...">
        <ul class="pager">
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
                {% endif %}    
                <li>第{{page_obj.number}}页 / 共{{ paginator.num_pages }}页</li>
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">下一页</a></li>
                {% endif %}

            {% endif %}
        </ul>
        </nav>
{% endblock %}